### ISSUE TITLE
Add ability to use blackhole routes instead of an Address List

### ISSUE THREAD

**Issue by Zebble** [flazzarini/blocklister#1]
Using blackhole routes should offer better overall performance, and the ability to add much larger blacklists to lesser hardware.

BGP could also be used, and I could put together some instructions on the overall BGP "Server" and Mikrotik side if you wish?  We have a very similar in-house BGP blacklist solution, but with far fewer lists than what you've included, so a combined effort may help?  How our BGP stuff works:

-  Installed a FreeBSD server.
-  Installed and configured OpenBGPD as an "anonymous" BGP server.  This allowed us to control access at the firewall level and not have to worry about adding every site Mikrotik to the BGP config.
-  bgpd.conf contains an include statement to a separate .conf file that includes the blacklist entries we're going to create and update with our script.
-  Created a route list with a private AS and community to house our blacklist.
-  On the Mikrotik, added a BGP peer pointing to the OpenBSD server and private AS.
-  On the Mikrotik, created 2 route filters: 1 to transform the private AS/BGP Community into blackhole routes, and the second to filter all outbound routes (unneeded/waste of bandwidth).

Then, nightly we run a script that updates the included .conf file on the OpenBGPD server.  Then we run a simple "bgpctl reload" to have OpenBGPD reload the configuration and update its routes.

This immediately sends add/remove commands to all connected Mikrotik BGP peers and routes are almost instantaneously updated.  Routes never need to be completely removed on the connected Mikrotiks, so they are never vulnerable for a second!

**Comment by flazzarini** [comment]
Hi there,

sounds like a good idea, thanks for your explications there. But what would you like to have as an output on via `blocklister`? Should it be a MikroTik specific set of commands or a `OpenBGPD` specific set of commands/config?

Thanks for clearing that up.

**Comment by Zebble** [comment]
Hi flazzarini,

Something that OpenBGPD could use would be ideal.  Here's an example out of my current bgpd-blacklist.conf file:

network 1.10.16.0/20 set community 65086:86     #Spamhaus

In general form:

network [blacklist IP/CIDR] set community [BGP community]     # [comment]

So perhaps an API format of something like:

https://blocklister.gefoo.org/ads?format=openbgpd&comment=Ads&bgpcommunity=65086:86

??

**Comment by flazzarini** [comment]
Great idea. 

**But** with the current architecture it would be to slow to convert source ip ranges to CIDR notations. 

Just a quick recap currently the files are being downloaded by the `updater` daemon thread and store as text files on disk. When I receive a `HTTP GET` request I simple read the file from disk an return the parsed entries back to the user using the MikroTik address list template. Some of these source list are constructed using `ip-ip` range notation or `CIDR` notation, so I have no control of that at the moment.

One option would be (and I've had that in mind already) is to have the `updater` thread do the job of converting `ip-ip` range notation to `CIDR` notations.

I clearly see another important feature here is to be able to render blocklists for different types of equipment (MikroTik, Juniper, etc.). That's also something to keep in mind.

I will consider this for the next major release!
