### ISSUE TITLE
Level1/2/3 lists are failing with HTTP error 500

### ISSUE THREAD

**Issue by PavelGorbanj** [flazzarini/blocklister#10]
https://blocklister.gefoo.org/level1
https://blocklister.gefoo.org/level2
https://blocklister.gefoo.org/level3

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, admin@gefoo.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.22 (Ubuntu) Server at blocklister.gefoo.org Port 443

**Comment by flazzarini** [comment]
Should be working again. *level1* *level2* and *level3* lists are actually quite big and therefor the ip deduplication feature of blocklister consumed a lot of RAM which made the main thread crash.

In the latest release v1.7.1 I've added a feature to disable deduplication of certain lists (such as level1, level2 and level3)
