### ISSUE TITLE
Add ability to request multiple lists in a single request

### ISSUE THREAD

**Issue by Zebble** [flazzarini/blocklister#2]
Using multiple lists currently requires sending a request per list.  Perhaps being able to specify multiple lists in a single call would be helpful?  For example:

https://blocklister.gefoo.org/multilist?lists=ads,openbl,openbl_180&comments=Ads,OpenBL,OpenBL_180&listname=blocklist

**Comment by flazzarini** [comment]
That's a great idea which could be implemented **right away**.

**Comment by flazzarini** [comment]
However multiple different comments will not be possible!
