### ISSUE TITLE
Ads list only adding 13 entires (using blocklister.gefoo.org)

### ISSUE THREAD

**Issue by shed909** [flazzarini/blocklister#6]
I'm not sure if it's the server or an issue on my hAP Lite, however I'm consistently only getting 13 entries when I run ad.rsc.

I've also got BlocklistDE and Spyware on a schedule which consistently get 20, 000+ addresses for BlocklistDE and 130+ for Spyware, so I don't think it's a RAM thing.

**Comment by flazzarini** [comment]
Hi there,

not sure why this is if you open up https://blocklister.gefoo.org/ads using your browser it presents you will all the ip ranges that will be added to the address list. And the result I just got was more than 13 entries.

Could you verify your mikrotik logs when running the script? Maybe there is an overlap in ip addresses, that might be an issue that I am aware of.

Also I haven't tried running this on an hAP Lite. I got one at home which is currently serving another purpose but I could try it out if needed.

**Comment by shanehull** [comment]
I'll have another look tonight.

I couldn't see much on the logs, but I also forgot to enable either Scripts, or Firewall on the logs (one of the two).
I'll enable both and let you know what it spits out, but if it's working on your end, I'm sure the issue is on mine.

**Comment by shanehull** [comment]
Okay, checked this out again and it appears you might be correct.

I get the following after it successfully adds 13 entries:
`19:22:29 script,error script error: failure: already have such entry`

**Comment by shanehull** [comment]
Confirmed. I removed the duplicate and re-ran the script. It added 156 entries following this - so there might be a few duplicates in there!

**Comment by dancadman** [comment]
I can confirm that there are several duplicates.  I copied it into Notepad++ and removed the duplicates one at a time until they were all gone.  I think there were four or five.

**Comment by NevRA** [comment]
Same story with duplicates. Can you update list plz?

**Comment by naturalnetworks** [comment]
+1 on seeing duplicates.

**Comment by gcormier** [comment]
First dupe is

`5.150.195.167-5.150.195.169`

**Comment by flazzarini** [comment]
Hi there,

I've activated the `deduplication` feature on the server which is running behind `blocklister.gefoo.org`. So you shouldn't have duplicates on the `/ads` list anymore.

However I would like to point out that I am not the owner of these lists! Most of the lists I use to reconvert into mikrotik address lists are sourced from https://www.iblocklist.com so I have no control over the entries on these lists.

Another point to add here is that I get the feeling that these duplicates occure more often than expected and I should maybe consider already filtering them out using the `blocklist-updater` process that way I could save a lot of CPU process power when compiling them to mikrotik address lists.

**Comment by gcormier** [comment]
@flazzarini Apprieciate it! And I realize you don't make the lists! Just ran an import and it worked!
