### ISSUE TITLE
Level2 List fails with 500 Internal server error

### ISSUE THREAD

**Issue by omata** [flazzarini/blocklister#8]
Hello,

Just reporting that **level2** list is returning `500 server error`.

Best regards.

**Comment by flazzarini** [comment]
Should be working again. *level1* *level2* and *level3* lists are actually quite big and therefor the ip deduplication feature of blocklister consumed a lot of RAM which made the main thread crash.

In the latest release v1.7.1 I've added a feature to disable deduplication of certain lists (such as level1, level2 and level3)
