### ISSUE TITLE
The *.gefoo.org certificate is expired

### ISSUE THREAD

**Issue by egor-n** [flazzarini/blocklister#9]
<img src="https://user-images.githubusercontent.com/378493/51085945-c31c3280-1748-11e9-8e11-e82a8bca4ecd.png" height=350px/>

**Comment by flazzarini** [comment]
Hi there,

yes I am aware of this. I will take care of this in the coming days. Sorry for the inconvenience.

**Comment by flazzarini** [comment]
Hi there I've just updated the certificate on `blocklister.gefoo.org`. Thanks for the patience
